const items = [
    "Upgrade Core (Low)",
    "Force Core (Low)",
    "Slot Extender (Low)",
    "Upgrade Core (Medium)",
    "Force Core (Medium)",
    "Slot Extender (Medium)",
    "Upgrade Core (High)",
    "Force Core (High)",
    "Slot Extender (High)",
    "Upgrade Core (Highest)",
    "Force Core (Highest)",
    "Slot Extender (Highest)",
    "Upgrade Core (Ultimate)",
    "Force Core (Ultimate)",
    "Slot Extender (Ultimate)",
    "Astral Core (Bluestin)",
    "Material Core (Bluestin)",
    "Quartz Core (Bluestin)",
    "Astral Core (Titanium)",
    "Material Core (Titanium)",
    "Quartz Core (Pherystin)",
    "Astral Core (Shadow Titanium)",
    "Material Core (Shadow Titanium)",
    "Quartz Core (Aqua)",
    "Astral Core (Osmium)",
    "Material Core (Osmium)",
    "Quartz Core (Lapis)",
    "Astral Core (Red Osmium)",
    "Material Core (Red Osmium)",
    "Quartz Core (Topaz)",
    "Astral Core (SIGMetal)",
    "Material Core (SIGMetal)",
    "Quartz Core (SIGMetal)",
    "Astral Core (Mithril)",
    "Material Core (Mithril)",
    "Quartz Core (Mithril)",
    "Astral Core (Archridium)",
    "Material Core (Archridium)",
    "Quartz Core (Archridium)",
    "Astral Core (Blue Mithril)",
    "Material Core (Blue Mithril)",
    "Quartz Core (Blue Mithril)",
    "Material Core (Bike)",
    "Astral Core (Palladium)",
    "Material Core (Palladium)",
    "Quartz Core (Palladium)",
    "Astral Core (Demonite)",
    "Material Core (Demonite)",
    "Quartz Core (Demonite)",
    "Pherystin Orb +5",
    "Pherystin Crystal +5",
    "Titanium Chakram +5",
    "Titanium Great Sword +5",
    "Titanium Blade +5",
    "Titanium Daikatana +5",
    "Titanium Katana +5",
    "Titanium Helmet +5",
    "Titanium Suit +5",
    "Titanium Gloves +5",
    "Titanium Boots +5",
    "Bluestin Epaulet of Fighter",
    "Sage's Bluestin Epaulet",
    "Guardian's Bluestin Epaulet",
    "Belt of Speed +4",
    "Belt of Vitality",
    "Belt of Protection",
    "Fighters Titanium Epaulet",
    "Titanium Epaulet of Sage",
    "Guardian's Titanium Epaulet",
    "Aqua Orb +5",
    "Aqua Crystal +5",
    "Shadow Titanium Chakram +5",
    "Shadow Titanium Great Sword +5",
    "Shadow Titanium Blade +5",
    "Shadow Titanium Daikatana +5",
    "Shadow Titanium Katana +5",
    "Shadow Titanium Helmet +5",
    "Shadow Titanium Suit +5",
    "Shadow Titanium Gloves +5",
    "Shadow Titanium Boots +5",
];

exports.items = items;